name: build release candidate on main merge

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry --version
          poetry check --no-interaction
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Test with pytest
        run: |
          poetry run pytest -v

      - name: Add version to environment
        run: |
          PROJECT_VERSION=$(poetry version --short)
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV

      - name: Build distribution artifects
        run: |
          poetry build --no-interaction

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          generate_release_notes: true
          draft: true
          files: |
            dist/application-${{ env.PROJECT_VERSION }}-py3-none-any.whl
            dist/application-${{ env.PROJECT_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
